# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import exemplo_pb2 as exemplo__pb2


class CalculadoraStub(object):
    """Definição do serviço da calculadora
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculaOperandos = channel.unary_unary(
                '/Calculadora/CalculaOperandos',
                request_serializer=exemplo__pb2.OperandosRequest.SerializeToString,
                response_deserializer=exemplo__pb2.ResultadoResponse.FromString,
                )


class CalculadoraServicer(object):
    """Definição do serviço da calculadora
    """

    def CalculaOperandos(self, request, context):
        """Envia os operandos e retorna o resultado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculaOperandos': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculaOperandos,
                    request_deserializer=exemplo__pb2.OperandosRequest.FromString,
                    response_serializer=exemplo__pb2.ResultadoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculadora(object):
    """Definição do serviço da calculadora
    """

    @staticmethod
    def CalculaOperandos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculadora/CalculaOperandos',
            exemplo__pb2.OperandosRequest.SerializeToString,
            exemplo__pb2.ResultadoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
