/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LAB1_A_H_RPCGEN
#define _LAB1_A_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int vetor_len;
	float *vetor_val;
} vetor;

#define PROG 100
#define VERSAO 10

#if defined(__STDC__) || defined(__cplusplus)
#define MENOR 1
extern  float * menor_10(vetor *, CLIENT *);
extern  float * menor_10_svc(vetor *, struct svc_req *);
#define MAIOR 2
extern  float * maior_10(vetor *, CLIENT *);
extern  float * maior_10_svc(vetor *, struct svc_req *);
extern int prog_10_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MENOR 1
extern  float * menor_10();
extern  float * menor_10_svc();
#define MAIOR 2
extern  float * maior_10();
extern  float * maior_10_svc();
extern int prog_10_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vetor (XDR *, vetor*);

#else /* K&R C */
extern bool_t xdr_vetor ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LAB1_A_H_RPCGEN */
